import fs from "node:fs"
import fsp from "node:fs/promises"
import path from "node:path"

/**
 * Write the given plugin manifest path into the user's local JSONC
 * plugins overlay.
 *
 * As of the JSONC migration the overlay is `zenbu.plugins.local.jsonc`
 * (gitignored). This function is the single point of truth used by both
 * `plugin-installer` (clone-and-install) and `plugin-dev` (Install
 * Plugin button on a locally scaffolded plugin) so the on-disk state is
 * consistent across entry points.
 *
 * Strategy:
 *
 *   1. If the file doesn't exist, create it with `{ "plugins": [...] }`
 *      and a header comment explaining how to edit it.
 *   2. If the file exists, parse it (JSONC \u2014 comments + trailing
 *      commas tolerated), check whether the manifest path is already
 *      present, and append if not. If a previously-disabled entry
 *      exists, flip it back to `enabled: true` instead of duplicating.
 *
 * The function is text-aware but not AST-aware: when we rewrite the file
 * we emit a canonical layout (two-space indent, one entry per line) and
 * drop any prior comments. This is the same trade-off the original
 * `zenbu.local.ts` patcher made; the local overlay is shape-restricted
 * and machine-edited, so losing comments on rewrite is acceptable.
 */
export async function patchLocalPlugins(
  projectDir: string,
  manifestPath: string,
): Promise<void> {
  const overlayPath = path.join(projectDir, "zenbu.plugins.local.jsonc")
  const absManifest = path.isAbsolute(manifestPath)
    ? manifestPath
    : path.resolve(projectDir, manifestPath)

  if (!fs.existsSync(overlayPath)) {
    const body = renderOverlay(
      [{ path: absManifest, enabled: true }],
      { withHeader: true },
    )
    await fsp.writeFile(overlayPath, body, "utf8")
    return
  }

  const raw = await fsp.readFile(overlayPath, "utf8")
  let parsed: unknown
  try {
    parsed = parseJsonc(raw)
  } catch {
    // Corrupt/unparseable overlay \u2014 keep the bad file around as a
    // sibling so the user can recover, then rewrite.
    const backupPath = nextAvailablePath(
      projectDir,
      "zenbu.plugins.local.previous",
      ".jsonc",
    )
    await fsp.rename(overlayPath, backupPath)
    const body = renderOverlay(
      [{ path: absManifest, enabled: true }],
      { withHeader: true },
    )
    await fsp.writeFile(overlayPath, body, "utf8")
    return
  }

  const entries: Array<{ path: string; enabled?: boolean; args?: unknown }> =
    isPlainObject(parsed) && Array.isArray((parsed as { plugins?: unknown }).plugins)
      ? ((parsed as { plugins: unknown[] }).plugins.filter(isPlainObject) as Array<{
          path: string
          enabled?: boolean
          args?: unknown
        }>)
      : []

  const overlayDir = path.dirname(overlayPath)
  const normalize = (entryPath: string): string =>
    path.isAbsolute(entryPath) ? entryPath : path.resolve(overlayDir, entryPath)

  const existing = entries.find((e) => normalize(e.path) === absManifest)
  if (existing) {
    if (existing.enabled !== false) return // already enabled, idempotent
    existing.enabled = true
  } else {
    entries.push({ path: absManifest, enabled: true })
  }

  await fsp.writeFile(overlayPath, renderOverlay(entries, { withHeader: false }), "utf8")
}

/**
 * Walk up from `startDir` (defaults to `process.cwd()`) looking for the
 * project root — the directory that contains `zenbu.config.ts`. We
 * patch `zenbu.plugins.local.jsonc` next to it.
 */
export function findProjectRoot(startDir?: string): string {
  let dir = startDir ?? process.cwd()
  for (let i = 0; i < 12; i++) {
    if (fs.existsSync(path.join(dir, "zenbu.config.ts"))) return dir
    const parent = path.dirname(dir)
    if (parent === dir) break
    dir = parent
  }
  return startDir ?? process.cwd()
}

// ---------------------------------------------------------------------------
//                                  internals

function renderOverlay(
  entries: Array<{ path: string; enabled?: boolean; args?: unknown }>,
  opts: { withHeader: boolean },
): string {
  const lines: string[] = []
  if (opts.withHeader) {
    lines.push(
      "// Auto-generated by the plugin-installer plugin.",
      "// Per-developer overrides \u2014 entries here are layered on top of",
      "// `zenbu.plugins.jsonc`. Flip `enabled` to disable a plugin without",
      "// removing it. Edits hot-reload like any other JSONC manifest.",
    )
  }
  lines.push("{")
  lines.push(`  "plugins": [`)
  entries.forEach((entry, idx) => {
    const parts: string[] = []
    parts.push(`"path": ${JSON.stringify(entry.path)}`)
    if (entry.enabled !== undefined) {
      parts.push(`"enabled": ${entry.enabled ? "true" : "false"}`)
    }
    if (entry.args !== undefined) {
      parts.push(`"args": ${JSON.stringify(entry.args)}`)
    }
    const comma = idx < entries.length - 1 ? "," : ""
    lines.push(`    { ${parts.join(", ")} }${comma}`)
  })
  lines.push(`  ]`)
  lines.push("}")
  return lines.join("\n") + "\n"
}

/**
 * Minimal JSONC parser \u2014 strips line/block comments and trailing
 * commas, then runs `JSON.parse`. Same shape as the helper inside
 * `@zenbujs/core`'s plugin-manifests module; duplicated here so the
 * plugin doesn't have to reach into core internals at runtime.
 */
function parseJsonc(source: string): unknown {
  let out = ""
  let i = 0
  const n = source.length
  while (i < n) {
    const ch = source[i]
    if (ch === '"') {
      const start = i
      i++
      while (i < n) {
        const c = source[i]
        if (c === "\\") {
          i += 2
          continue
        }
        if (c === '"') {
          i++
          break
        }
        i++
      }
      out += source.slice(start, i)
      continue
    }
    if (ch === "/" && source[i + 1] === "/") {
      i += 2
      while (i < n && source[i] !== "\n") i++
      continue
    }
    if (ch === "/" && source[i + 1] === "*") {
      i += 2
      while (i < n && !(source[i] === "*" && source[i + 1] === "/")) i++
      i = Math.min(i + 2, n)
      continue
    }
    out += ch
    i++
  }
  const cleaned = out.replace(/,\s*(?=[\]}])/g, "")
  return JSON.parse(cleaned)
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value)
}

function nextAvailablePath(
  dir: string,
  base: string,
  ext: string,
): string {
  let candidate = path.join(dir, `${base}${ext}`)
  let n = 1
  while (fs.existsSync(candidate)) {
    n++
    candidate = path.join(dir, `${base}.${n}${ext}`)
  }
  return candidate
}
