import fs from "node:fs"
import fsp from "node:fs/promises"
import path from "node:path"

/**
 * Shared `zenbu.local.ts` transform.
 *
 * Originally lived inside `PluginInstallerService` next to the
 * git-clone install path. Lifted out so `plugin-dev` can call the
 * same patch when the user clicks "Install Plugin" on a locally
 * scaffolded plugin \u2014 same end-state on disk, no duplication.
 *
 * Strategy, in order of preference:
 *
 *  1. **File doesn't exist** \u2014 write a minimal one with the new
 *     entry. Trivial.
 *  2. **Simple-case detection** \u2014 scan the source for a literal
 *     array that is *either* directly `export default [ \u2026 ]` or
 *     bound to a `const X = [ \u2026 ]` whose name appears in
 *     `export default X`. If we find one, insert a string element
 *     at the end of the array. This keeps the user's existing
 *     formatting and any inline `definePlugin({...})` entries
 *     untouched.
 *  3. **Wrap fallback** \u2014 rename the existing file to
 *     `zenbu.local.previous.ts` and write a new `zenbu.local.ts`
 *     that imports it and concatenates. This handles arbitrary
 *     shapes (function-returning-array, dynamic logic, etc.) at
 *     the cost of one extra file. Repeated wraps stay flat by
 *     versioning the suffix.
 *
 * The transform is text-only \u2014 no TypeScript AST \u2014 because the
 * overlay file is by convention small and shape-restricted, and
 * the wrap fallback covers everything we can't pattern-match.
 */
export async function patchLocalPlugins(
  projectDir: string,
  manifestPath: string,
): Promise<void> {
  const localPath = path.join(projectDir, "zenbu.local.ts")
  const newEntry = JSON.stringify(manifestPath)

  if (!fs.existsSync(localPath)) {
    const body =
      `// Auto-generated by the plugin-installer plugin.\n` +
      `// Add or remove entries here to enable / disable user-installed plugins.\n` +
      `import type { LocalPluginsDefault } from "@zenbujs/core/config"\n\n` +
      `const plugins: LocalPluginsDefault = [\n` +
      `  ${newEntry},\n` +
      `]\n\n` +
      `export default plugins\n`
    await fsp.writeFile(localPath, body, "utf8")
    return
  }

  const original = await fsp.readFile(localPath, "utf8")

  // Idempotence: if the entry is already mentioned, no-op.
  if (original.includes(newEntry) || original.includes(manifestPath)) return

  // Try simple-case detection.
  const patched = tryInsertIntoArrayLiteral(original, newEntry)
  if (patched !== null) {
    await fsp.writeFile(localPath, patched, "utf8")
    return
  }

  // Wrap fallback. Pick a non-colliding "previous" filename so we
  // can wrap multiple times across multiple installs without ever
  // overwriting a real source file.
  const previousPath = nextAvailablePath(
    projectDir,
    "zenbu.local.previous",
    ".ts",
  )
  await fsp.rename(localPath, previousPath)
  const previousRel = "./" + path.basename(previousPath, ".ts")
  const wrapped =
    `// Auto-wrapped by the plugin-installer plugin.\n` +
    `// The previous overlay is preserved at ${path.basename(previousPath)}.\n` +
    `import previous from "${previousRel}"\n\n` +
    `const __previousArr = Array.isArray(previous) ? previous : [previous]\n` +
    `export default [...__previousArr, ${newEntry}]\n`
  await fsp.writeFile(localPath, wrapped, "utf8")
}

/**
 * Walk up from `startDir` (defaults to `process.cwd()`) looking for the
 * project root \u2014 the directory that contains `zenbu.config.ts`. We
 * patch `zenbu.local.ts` next to it.
 */
export function findProjectRoot(startDir?: string): string {
  let dir = startDir ?? process.cwd()
  for (let i = 0; i < 12; i++) {
    if (fs.existsSync(path.join(dir, "zenbu.config.ts"))) return dir
    const parent = path.dirname(dir)
    if (parent === dir) break
    dir = parent
  }
  return startDir ?? process.cwd()
}

// ---------------------------------------------------------------------------
// internals (verbatim from the original implementation; see comments above
// for the design rationale)

function tryInsertIntoArrayLiteral(
  source: string,
  entry: string,
): string | null {
  const directRe = /export\s+default\s*\(?\s*(\[)/m
  const direct = directRe.exec(source)
  if (direct) {
    const openIdx = direct.index + direct[0].length - 1
    const closeIdx = findMatchingBracket(source, openIdx)
    if (closeIdx !== -1) {
      return insertBeforeArrayClose(source, openIdx, closeIdx, entry)
    }
  }

  const defaultIdentRe = /export\s+default\s+([A-Za-z_$][\w$]*)\s*;?\s*$/m
  const defaultIdent = defaultIdentRe.exec(source)
  if (defaultIdent) {
    const name = defaultIdent[1]
    const bindingRe = new RegExp(
      `\\b(?:const|let|var)\\s+${escapeReg(name)}\\s*(?::[^=]+)?=\\s*(\\[)`,
      "m",
    )
    const binding = bindingRe.exec(source)
    if (binding) {
      const openIdx = binding.index + binding[0].length - 1
      const closeIdx = findMatchingBracket(source, openIdx)
      if (closeIdx !== -1) {
        return insertBeforeArrayClose(source, openIdx, closeIdx, entry)
      }
    }
  }

  return null
}

function insertBeforeArrayClose(
  source: string,
  openIdx: number,
  closeIdx: number,
  entry: string,
): string {
  const lineStart = source.lastIndexOf("\n", openIdx) + 1
  const indentMatch = /^[ \t]*/.exec(source.slice(lineStart, openIdx))
  const indent = (indentMatch?.[0] ?? "") + "  "

  const inner = source.slice(openIdx + 1, closeIdx)
  const trimmedInner = inner.trim()

  let insertion: string
  if (trimmedInner.length === 0) {
    insertion = `\n${indent}${entry},\n${indent.slice(2)}`
  } else {
    const needsComma = !/,\s*$/.test(inner)
    insertion =
      inner.replace(/\s*$/, "") +
      (needsComma ? "," : "") +
      `\n${indent}${entry},\n${indent.slice(2)}`
  }

  return (
    source.slice(0, openIdx + 1) + insertion + source.slice(closeIdx)
  )
}

function findMatchingBracket(s: string, openIdx: number): number {
  let depth = 0
  let i = openIdx
  while (i < s.length) {
    const ch = s[i]
    if (ch === "/" && s[i + 1] === "/") {
      const nl = s.indexOf("\n", i)
      i = nl === -1 ? s.length : nl + 1
      continue
    }
    if (ch === "/" && s[i + 1] === "*") {
      const end = s.indexOf("*/", i + 2)
      i = end === -1 ? s.length : end + 2
      continue
    }
    if (ch === '"' || ch === "'" || ch === "`") {
      i++
      while (i < s.length && s[i] !== ch) {
        if (s[i] === "\\") i += 2
        else i++
      }
      i++
      continue
    }
    if (ch === "[") depth++
    else if (ch === "]") {
      depth--
      if (depth === 0) return i
    }
    i++
  }
  return -1
}

function escapeReg(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
}

function nextAvailablePath(
  dir: string,
  base: string,
  ext: string,
): string {
  let candidate = path.join(dir, `${base}${ext}`)
  let n = 1
  while (fs.existsSync(candidate)) {
    n++
    candidate = path.join(dir, `${base}.${n}${ext}`)
  }
  return candidate
}
