import { useDb } from "@zenbujs/core/react"
import {
  ArrowDownIcon,
  ArrowUpIcon,
  DatabaseIcon,
  GaugeIcon,
} from "lucide-react"
import { StatusBarItem } from "./status-bar-item"

export type ChatStatsStatusItemProps = {
  /** The session whose stats to render. Pass explicitly so a status
   * bar embedded inside one pane shows *that* pane's session — not
   * whichever session happens to be focused window-wide. */
  sessionId: string | null
}

/**
 * Format token counts the same way pi's footer does
 * (modes/interactive/components/footer.js#formatTokens).
 */
function formatTokens(count: number): string {
  if (count < 1000) return count.toString()
  if (count < 10000) return `${(count / 1000).toFixed(1)}k`
  if (count < 1000000) return `${Math.round(count / 1000)}k`
  if (count < 10000000) return `${(count / 1000000).toFixed(1)}M`
  return `${Math.round(count / 1000000)}M`
}

/**
 * Session stats line. Where pi's terminal footer uses single-character
 * sigils (`↑ ↓ R W`), we spell things out with small icons + words so
 * the meaning is obvious at a glance.
 *
 * Model / thinking level live in the composer toolbar above, not here.
 */
export function ChatStatsStatusItem({ sessionId }: ChatStatsStatusItemProps) {
  const stats = useDb(root => {
    if (!sessionId) return null
    return root.app.sessions[sessionId]?.stats ?? null
  })

  if (!stats) return null

  const { tokens, cost, contextUsage, autoCompactionEnabled } = stats

  // Combine cache read + write into a single "cached" figure. The split
  // is mostly debugging detail — full numbers are in the tooltip.
  const cacheTotal = (tokens.cacheRead ?? 0) + (tokens.cacheWrite ?? 0)

  let contextTone: "default" | "warning" | "danger" = "default"
  let contextLabel: string | null = null
  if (contextUsage) {
    const cw = formatTokens(contextUsage.contextWindow)
    if (contextUsage.percent === null) {
      contextLabel = `?% of ${cw}`
    } else {
      contextLabel = `${contextUsage.percent.toFixed(0)}% of ${cw}`
      if (contextUsage.percent > 90) contextTone = "danger"
      else if (contextUsage.percent > 70) contextTone = "warning"
    }
  }

  const hasAnyStats =
    tokens.input > 0 ||
    tokens.output > 0 ||
    cacheTotal > 0 ||
    !!cost ||
    !!contextLabel

  if (!hasAnyStats) return null

  return (
    <>
      {tokens.input > 0 && (
        <StatusBarItem
          icon={<ArrowUpIcon className="size-3" />}
          title={`Input tokens sent to the model: ${tokens.input.toLocaleString()}`}
        >
          {formatTokens(tokens.input)} in
        </StatusBarItem>
      )}
      {tokens.output > 0 && (
        <StatusBarItem
          icon={<ArrowDownIcon className="size-3" />}
          title={`Output tokens generated by the model: ${tokens.output.toLocaleString()}`}
        >
          {formatTokens(tokens.output)} out
        </StatusBarItem>
      )}
      {cacheTotal > 0 && (
        <StatusBarItem
          icon={<DatabaseIcon className="size-3" />}
          title={
            `Prompt cache — reused tokens avoid re-billing.\n` +
            `Read ${(tokens.cacheRead ?? 0).toLocaleString()} • ` +
            `Written ${(tokens.cacheWrite ?? 0).toLocaleString()}`
          }
        >
          {formatTokens(cacheTotal)} cached
        </StatusBarItem>
      )}
      {!!cost && (
        <StatusBarItem title={`Estimated cost so far: $${cost.toFixed(4)}`}>
          ${cost.toFixed(3)}
        </StatusBarItem>
      )}
      {contextLabel && contextUsage && (
        <StatusBarItem
          icon={<GaugeIcon className="size-3" />}
          tone={contextTone}
          title={
            `Context window usage: ` +
            `${contextUsage.tokens?.toLocaleString() ?? "?"} of ` +
            `${contextUsage.contextWindow.toLocaleString()} tokens` +
            (autoCompactionEnabled
              ? `\nAuto-compaction is on — older turns will be summarized as you approach the limit.`
              : ``)
          }
        >
          {contextLabel}
          {autoCompactionEnabled && (
            <span className="ml-1 opacity-60">auto</span>
          )}
        </StatusBarItem>
      )}
    </>
  )
}
